---
title: "functions-tutorial"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Work with some data in degrees F


- Convert to C
  
```{r}

source("convert.R") #add own functions to work inside local environments

airtemps <- c(212, 100, 32, 64, 0, 20)

#airtemp1 <- (airtemps[1]-32)*5/9

airtemp_all <- (airtemps-32)*5/9

new_fahr_to_celsius(airtemps)

```



# Write a function to do that

```{r}
fahr_to_celsius <- function (fahr){
  celsius <- (fahr-32)*5/9
  return(celsius)
}

celsius_temps <- fahr_to_celsius(airtemps)
celsius_temps

```


# Write a function to go C to F

```{r}

celsius_to_fahr <- function(celsius){
  fahr <- celsius*9/5+32
  return (fahr)
}

fahr_temp_new <- celsius_to_fahr(celsius_temps)
fahr_temp_new == airtemps


```


# Show how to document Functions


```{r}
#' Converts numeric temperature data from degrees Fahrenheit to degree Celsius
#'
#' @param fahr the value in Fahrenheit to be converted
#' @return the converted value in Celsius

fahr_to_celsius <- function (fahr){
  celsius <- (fahr-32)*5/9
  return(celsius)
}



